import { Inter, Syne } from "next/font/google";
import React from "react";

import { Footer } from "@/components/templates/Footer";
import { Header } from "@/components/templates/Header";
import { cn } from "@/shared/lib/utils";

import type { Metadata } from "next";


import "./globals.css";


const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  display: "swap",
});

const syne = Syne({
  subsets: ["latin"],
  variable: "--font-syne",
  display: "swap",
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        {/* Prevent theme flash on first paint */}
        <script dangerouslySetInnerHTML={{
          __html: `
          (() => {
            try {
              const key = 'theme';
              const stored = localStorage.getItem(key);
              const prefersDark = window.matchMedia('(prefers-color-scheme: dark)').matches;
              const theme = stored || (prefersDark ? 'dark' : 'light');
              const root = document.documentElement;
              // Toggle either .dark or data-theme depending on your strategy
              if (theme === 'dark') {
                root.classList.add('dark');          // OR: root.setAttribute('data-theme','dark')
              } else {
                root.classList.remove('dark');       // OR: root.setAttribute('data-theme','light')
              }
            } catch {}
          })();`
        }} />
      </head>

      <body className={cn("min-h-screen bg-background text-foreground", `${inter.variable} ${syne.variable} `)}>
        <Header />
        <main className="container mx-auto px-4 py-10">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
